version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python manage.py runserver 0.0.0.0:8080'
    volumes:
      - .:/dockerapp
    ports:
      - 8080:8080
    depends_on:
      - db

  rabbit:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python -u consumer.py'
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mydb2
    env_file:
      - environment.env
    ports:
      - 5433:5432
