# Generated by Django 3.2.6 on 2021-08-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_patient_allergies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=models.JSONField(default=None, null=True),
        ),
    ]
