# Generated by Django 3.2.7 on 2021-09-03 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OurPrescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(max_length=100)),
                ('patient_name', models.CharField(max_length=100)),
                ('doctor_id', models.IntegerField()),
            ],
        ),
    ]
