# Generated by Django 3.2.7 on 2021-09-03 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_pickedupprescriptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pickedupprescriptions',
            old_name='patinet_name',
            new_name='patient_name',
        ),
    ]
